### ISSUE TITLE
Mission Report

### ISSUE THREAD

**Issue by EureHeiserkeit** [Dozentenampel/dozentenampel.github.io#1]
Florian
Erweiterung des Reports für alle Mitglieder
Reporting aller Mitglieder in einer Datei in unterschiedlichen Blättern
bis 26.10.21
Ablage in diesem ToDo

**Comment by Hesus002** [comment]
[Mission.Report.1.0.xlsx](https://github.com/Dozentenampel/dozentenampel.github.io/files/7461730/Mission.Report.1.0.xlsx)

**Comment by Hesus002** [comment]
[Mission.Report.1.1.xlsx](https://github.com/Dozentenampel/dozentenampel.github.io/files/7461758/Mission.Report.1.1.xlsx)

**Comment by EureHeiserkeit** [comment]
[Mission.Report.1.1.xlsx](https://github.com/Dozentenampel/dozentenampel.github.io/files/7497458/Mission.Report.1.1.xlsx)
