### ISSUE TITLE
Dozentenumfrage Aufwandbereitschaft E-Mail Formulierung

### ISSUE THREAD

**Issue by Hesus002** [Dozentenampel/dozentenampel.github.io#18]
Jennifer & Florian

E-Mail Text für 2. Umfrage schreiben

bis 06.12.21

Präsentation am 06.12.21
+ Eintrag in Wiki

Planning Poker: 5

**Comment by netzljnw** [comment]
[](url
[Sehr geehrte Lehrkräfte und Mitarbeiter der FH SWF Hagen.docx](https://github.com/Dozentenampel/dozentenampel.github.io/files/7704183/Sehr.geehrte.Lehrkrafte.und.Mitarbeiter.der.FH.SWF.Hagen.docx)
)
