### ISSUE TITLE
Dozentenumfrage Aufwandsbereitschaft

### ISSUE THREAD

**Issue by Hesus002** [Dozentenampel/dozentenampel.github.io#19]
Kai & Susanna

E-Mail rausschicken, Erinnern falls zu wenig Rückmeldung, Auswertung

bis 20.12.21

Präsentation am 20.12.21
+ Ergänzung der Hypothesen

Planning Poker: 8

**Comment by Hesus002** [comment]
Weiß:
15 min pro Tag
Idee: Calendly

Femmer:
3 min

Wehmeier:
Flexibilität durch ausschließlich Online-Kommunikation

**Comment by Hesus002** [comment]
Sonneborn: 
Nein, da ich meine Sprechstunde in meinen Veranstaltungen klar kommuniziere und ansonsten über Mail und Moodle jederzeit bereitstehe, eine individuelle Kommunikation (zoom, mail, Telefon, pers. Gespräch) zeitnah zu vereinbaren. Insbesondre bin ich so in der Lage, zu differenzieren. Wenn ich Studierenden mit einem dringlichen Anliegen evtl. sogar einen Abendtermin anbiete, so werden sich andererseits diejenigen, die vergessen haben, ihre Unterlagen abzuholen, z.B. bis zu meiner nächsten Sprechstunde gedulden müssen. 
Da kann ich durch generelle Verfügbarkeitsangaben nicht abbilden.
Daher sehe ich den Mehrwert einer solchen Plattform für mich als nicht gegeben und damit auch keinen Zeitaufwand zu dessen Pflege als sinnvolle Investition an.

**Comment by Hesus002** [comment]
Fleischer: 
30 Min pro Woche

**Comment by Hesus002** [comment]
de Vries:

5 min pro Woche

**Comment by kapue002** [comment]
[Auswertung Dozentenbefragung.xlsx](https://github.com/Dozentenampel/dozentenampel.github.io/files/7745358/Auswertung.Dozentenbefragung.xlsx)
