### ISSUE TITLE
Umfrage Bedarf

### ISSUE THREAD

**Issue by Hesus002** [Dozentenampel/dozentenampel.github.io#5]
Florian
Befragung von 20 Studierende und 5 Lehrkräfte / Profs, ob Interesse oder nicht
Bedarf ermitteln
bis 08.11.21
Ablage in diesem ToDo

**Comment by EureHeiserkeit** [comment]
[Umfrage1_Agile.xlsx](https://github.com/Dozentenampel/dozentenampel.github.io/files/7497042/Umfrage1_Agile.xlsx)

**Comment by EureHeiserkeit** [comment]
Bedarfsermittlung ausschließlich über Studierende durchgeführt
