### ISSUE TITLE
Umfrage Funktionalität

### ISSUE THREAD

**Issue by Hesus002** [Dozentenampel/dozentenampel.github.io#6]
Jennifer
Umfrage bei 25 Studierenden, welche Funktionalitäten gewünscht sind
Erster Einblick in den erwarteten Funktionsumfang
bis zum 15.11.21
Ablage in diesem ToDo
Planning Poker: 8

**Comment by netzljnw** [comment]
Ergebnisse: https://app.lamapoll.de/#/poll/307767/results/general
